@ECHO OFF

REM AGREGAR EN EL PATH DEL S.O. C:\Program Files\Git\cmd
REM AGREGAR EN EL PATH DEL S.O. C:\Program Files\Git\bin\git.exe

TITLE INSTALANDO DEPENDENCIAS

REM INSTALAR NUEVAS DEPENDENCIAS
ECHO ==== NPM INSTALL ====
CALL npm install
ECHO: 

PAUSE



