@ECHO OFF

REM AGREGAR EN EL PATH DEL S.O. C:\Program Files\Git\cmd
REM AGREGAR EN EL PATH DEL S.O. C:\Program Files\Git\bin\git.exe

TITLE DESCARGANDO LOS CAMBIOS

REM ACTUALIZAR LOS CAMBIOS DESDE EL REPOSITORIO
ECHO ==== GIT PULL ====
CALL git pull
ECHO:



