//TIPO PARAMETRO 1
export const PARAMETRO_ACTIVO = 1
export const PARAMETRO_ACTIVO_S = 'ACTIVO'

export const PARAMETRO_INACTIVO = 2
export const PARAMETRO_INACTIVO_S = 'INACTIVO'

//TIPO PARAMETRO 2
export const PARAMETRO_MASCULINO = 3
export const PARAMETRO_MASCULINO_S = 'MASCULINO'

export const PARAMETRO_FEMENINO = 4
export const PARAMETRO_FEMENINO_S = 'FEMENINO'

//TIPO PARAMETRO 3
export const PARAMETRO_A_MAS = 5
export const PARAMETRO_A_MAS_S = 'A+'

export const PARAMETRO_B_MENOS = 6
export const PARAMETRO_B_MENOS_S = 'B+'

//TIPO PARAMETRO 4
export const PARAMETRO_PENDIENTE = 7
export const PARAMETRO_PENDIENTE_S = 'PENDIENTE'

export const PARAMETRO_EN_REVISION = 8
export const PARAMETRO_EN_REVISION_S = 'EN REVISION'

export const PARAMETRO_ATENDIDO = 9
export const PARAMETRO_ATENDIDO_S = 'ATENDIDO'

////TIPO PARAMETRO 5
export const PARAMETRO_ESSALUD = 10
export const PARAMETRO_ESSALUD_S = 'ESSALUD'

export const PARAMETRO_SIS = 11
export const PARAMETRO_SIS_S = 'SIS'

////TIPO PARAMETRO 6
export const PARAMETRO_SIN_ESPECIFICAR = 12
export const PARAMETRO_SIN_ESPECIFICAR_S = 'SIN ESPECIFICAR'

export const PARAMETRO_II_1 = 13
export const PARAMETRO_II_1_S = 'II-1'

export const PARAMETRO_II_2 = 14
export const PARAMETRO_II_2_S = 'II-2'

export const PARAMETRO_I_3 = 15
export const PARAMETRO_I_3_S = 'I-3'

export const PARAMETRO_I_4 = 16
export const PARAMETRO_I_4_S = 'I-4'

//TIPO PARAMETRO 7
export const PARAMETRO_DNI = 17
export const PARAMETRO_DNI_S = 'DNI'

export const PARAMETRO_CODIGO_EMPADRONAMIENTO = 18
export const PARAMETRO_CODIGO_EMPADRONAMIENTO_S = 'CODIGO EMPADRONAMIENTO'

//TIPO PARAMETRO 8
export const PARAMETRO_CREADO = 19
export const PARAMETRO_CREADO_S = 'CREADO'

export const PARAMETRO_DIAGNOSTICADO_POR_ENFERMERO = 20
export const PARAMETRO_DIAGNOSTICADO_POR_ENFERMERO_S = 'DIAGNOSTICADO POR ENFERMERO'

export const PARAMETRO_CITA_CREADA = 21
export const PARAMETRO_CITA_CREADA_S = 'CITA CREADA'

export const PARAMETRO_DIAGNOSTICADO_POR_MEDICO = 22
export const PARAMETRO_DIAGNOSTICADO_POR_MEDICO_S = 'DIAGNOSTICADO POR MEDICO'

export const PARAMETRO_CONSULTADO_A_MEDICO_ESPECIALISTA = 23
export const PARAMETRO_CONSULTADO_A_MEDICO_ESPECIALISTA_S = 'CONSULTADO A MEDICO ESPECIALISTA'

export const PARAMETRO_FINALIZADO_POR_ENFERMERO = 24
export const PARAMETRO_FINALIZADO_POR_ENFERMERO_S = 'FINALIZADO POR ENFERMERO'

export const PARAMETRO_FINALIZADO_POR_MEDICO = 25
export const PARAMETRO_FINALIZADO_POR_MEDICO_S = 'FINALIZADO POR MEDICO'

//TIPO PARAMETRO 9
export const PARAMETRO_SIN_DIAGNOSTICO = 26
export const PARAMETRO_SIN_DIAGNOSTICO_S = 'SIN DIAGNOSTICO'

export const PARAMETRO_PRESUNTIVO = 27
export const PARAMETRO_PRESUNTIVO_S = 'PRESUNTIVO'

export const PARAMETRO_FINAL = 28
export const PARAMETRO_FINAL_S = 'FINAL'

export const PARAMETRO_CERRADO = 29
export const PARAMETRO_CERRADO_S = 'CERRADO'